### ISSUE TITLE
Debian 9 stretch linking broken without "-lz -lm" flags

### ISSUE THREAD

**Issue by billsimon** [kouya/snownews#15]
I had to do the following to get it to build on Debian 9:

* added `-lz -lm` to the ldconfig. I edited the `platform_settings` file and added these two libs to the end of LDFLAGS

* install gettext (`apt-get install gettext`) to provide the `msgfmt` tool

**Comment by kouya** [comment]
That's strange though. It shouldn't compile at all since stretch uses OpenSSL 1.1.0f which is incompatible. Do you have both libssl1.1 and libssl1.0 installed? Didn't even know this was possible. :)

**Comment by billsimon** [comment]
Yes, I have both of the SSL versions installed. On stretch you can apt-get
install both.

**Comment by kouya** [comment]
I've added gettext to the build requirements list in the README. Always assumed this was installed by default by virtually any distribution.

Not sure why -lz -lm is not picked up. It used to work, I think xml2-config pulled it.

Short term workaround is using
`EXTRA_LDFLAGS="-lz -lm" make`
or editing the platform_settings.

**Comment by kouya** [comment]
With the new build this one should work now. Please reopen if something is still fuzzy.
