### ISSUE TITLE
Use pkg-config to get libxml2 libs

### ISSUE THREAD

**Issue by msharov** [kouya/snownews#18]
The current version of libxml2 is shipped with a pkg-config file, so you can use pkg-config --libs libxml-2.0 to find the link list.

This is beneficial because xml2-config puts many unnecessary libraries in the libs list that are already linked to the shared libxml2. pkg-config is able to differentiate between linking to a shared libxml2 and a static one, and will only include -lxml2 in the former case. Among the libraries unnecessarily linked to is libicu, which annoyingly changes the major version number at every release, requiring rebuilds of every package using it. Converting to pkg-config will eliminate this problem, also fixing previously reported issue #3.

**Comment by kouya** [comment]
Oh, thanks, good suggestion. :) Code is kinda ancient.

**Comment by kouya** [comment]
Closing this then after merging your code.
