### ISSUE TITLE
Package new version

### ISSUE THREAD

**Issue by kouya** [kouya/snownews#28]
Adding this one, because I'm lazy and it will remind me constantly.

**Comment by msharov** [comment]
In case you are wondering, making a new release requires changing line 7 in configure to `PKG_VERSTR="v1.5.14"`, which will correctly substitute the new version number in distribution tarballs downloaded from the releases page. When run in a cloned git repository, configure will try a `git describe` to determine the version number, which will work as soon as you create the tag for the new release.

**Comment by kouya** [comment]
Should be done now.
