### ISSUE TITLE
1.6.10 `make install` fails

### ISSUE THREAD

**Issue by ilovezfs** [kouya/snownews#30]
```
==> Downloading https://github.com/kouya/snownews/archive/1.6.10.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/snownews-1.6.10.tar.gz
==> Verifying snownews-1.6.10.tar.gz checksum
tar xf /Users/joe/Library/Caches/Homebrew/snownews-1.6.10.tar.gz -C /private/tmp/d20180806-93215-17zorud
==> ./configure --prefix=/usr/local/Cellar/snownews/1.6.10
required library ncurses is missing
==> make install EXTRA_LDFLAGS= -L/usr/local/opt/openssl/lib -lz CC=clang
Makefile:1: Config.mk: No such file or directory
Running configure ...
required library ncurses is missing
make: *** No rule to make target `install'.  Stop.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make install EXTRA_LDFLAGS=\ -L/usr/local/opt/openssl/lib\ -lz CC=clang
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```
Also, note that macOS does not provide a `.pc` file for ncurses even though libncurses.dylib is provided by the system and ncurses.h is in the SDK.

**Comment by msharov** [comment]
pkgconfig was created because it is nearly impossible to portably find libraries. Instead of adopting [FHS](https://wiki.linuxfoundation.org/lsb/fhs), every platform and distribution goes to great lengths to hide library files in randomly named subdirs. Since it is impossible to get them all to abandon their misguided ways, the only solution is to keep pkgconfig working. So, to fix your problem, create /usr/lib/pkgconfig/ncurses.pc containing the location of ncurses library:

```
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: ncursesw
Description: ncurses 6.1 library
Version=6.1
Libs:  -lncursesw
Cflags:  -D_GNU_SOURCE -D_DEFAULT_SOURCE
```

**Comment by kouya** [comment]
Since there was no further feedback, closing this one.

**Comment by ryandesign** [comment]
> create /usr/lib/pkgconfig/ncurses.pc

/usr is protected by [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection) on macOS. Nobody other than Apple's OS updates, not even root, is allowed to modify it.

**Comment by msharov** [comment]
If you only can install to your local account, you can create a local pkg-config repository, say in ~/.local/lib/pkgconfig. Put the .pc file there. Add `export PKG_CONFIG_PATH=/usr/lib/pkgconfig:$HOME/.local/lib/pkgconfig` to your .bashrc .
