### ISSUE TITLE
Fail to load GitHub RSS

### ISSUE THREAD

**Issue by NIR-Ginko** [kouya/snownews#32]
I tried to load perrsonal GitHub RSS news feed but I can't add any. The error message says "Error in server reply".

What can I do to diagnose the problem? I suppose there is a problem with HTTPS but I have not enough information.

**Comment by kouya** [comment]
ptdel is correct. And sorry for taking so long to answer. There is no https support, but can use external tools.

The FAQ is on github as well btw: https://github.com/kouya/snownews/wiki/FAQ
I moved everything from the old site to github.
