### ISSUE TITLE
Remove openssl dependency

### ISSUE THREAD

**Issue by kouya** [kouya/snownews#6]
Openssl is only used for MD5 calculations. Best to drop that dependency and find another (working!) MD5.

**Comment by msharov** [comment]
It would be better to instead add support for https urls. Half the feeds I read are only available as https. The openssl API, on the other hand, is a nightmare. mbedtls is a better choice.

**Comment by kouya** [comment]
If you feel like adding https support, I'd be happy to merge any code. Or replace the whole http client with something entirely. Could be the better choice anyway rather than having a whole http client in there. But I honestly have no time to work on this.

I also don't cling to openssl. I would just require anything used to not be totally obscure (mbedtls aka PolarSSL now owned by arm? oook, interesting, but looks like it won't go away tomorrow) and be available from Debian stable.
